USE HR_ANALYSIS;

-- rename the table from `hr analytical dataset` to hr_data
rename table `hr analytical dataset` to hr_data;

-- DATA EXPLORATION 
DESCRIBE HR_DATA;
select * from hr_data 
limit 10;

--  REMOVE DUPLICATES
SELECT EMPLOYEE_ID ,COUNT(EMPLOYEE_ID) AS DUPLICATES
FROM HR_DATA
GROUP BY EMPLOYEE_ID
HAVING  DUPLICATES >1;

-- EXTRACT ONLY DATE
SELECT HIRE_DATE ,DATE(HIRE_DATE)
FROM HR_DATE;
UPDATE HR_DATA
SET HIRE_DATE = DATE(HIRE_DATE);

-- SPLIT COLUMN LOCATION USING THE DELIMITER ","
ALTER TABLE HR_DATA
MODIFY CITY VARCHAR(100),
MODIFY COUNTRY VARCHAR(100);
update hr_data
set city = trim(substrin(location ,',',1));
UPDATE hr_data
SET city = TRIM(SUBSTRING_INDEX(location, ',', 1));
-- DROP COLUMN AFTER SPLIT
alter table hr_data
drop column location;
-- HANDLE MISSING VALUES
SELECT * FROM HR_DATA
WHERE EMPLOYEE_ID IS NULL OR FULL_NAME IS NULL OR DEPARTMENT IS NULL OR JOB_TITLE IS NULL OR HIRE_DATE IS NULL
	OR Performance_Rating IS NULL OR Experience_Years IS NULL OR Status IS NULL OR Work_Mode IS NULL 
		 OR Salary_INR IS NULL OR CITY IS NULL OR COUNTRY IS NULL;

-- REMOVE UNWANTED SPACES
UPDATE hr_data
SET 
    Employee_ID = TRIM(Employee_ID),
    Full_Name = TRIM(Full_Name),
    Department = TRIM(Department),
    Job_Title = TRIM(Job_Title),
    Hire_Date = TRIM(Hire_Date),
    Performance_Rating = TRIM(Performance_Rating),
    Experience_Years = TRIM(Experience_Years),
    Status = TRIM(Status),
    Work_Mode = TRIM(Work_Mode),
    Salary_INR = TRIM(Salary_INR),
    city = trim(city),
    country = trim(country);

select * from hr_data
limit 5;
SELECT COUNT(EMPLOYEE_ID) 
FROM HR_DATA;
-- DISTINCT VALUES SELECTION
SELECT distinct DEPARTMENT
FROM HR_DATA;
select distinct STATUS 
FROM HR_DATA;
SELECT DISTINCT WORK_MODE 
FROM HR_DATA;
SELECT DISTINCT COUNTRY 
FROM HR_DATA;
-- CHECK THE RANGE OF NUMERICAL FIELDS
SELECT * 
FROM hr_data
WHERE Experience_Years < 0 
   OR Experience_Years > 40 
   OR Performance_Rating NOT BETWEEN 1 AND 5 
   OR Salary_INR < 10000;

-- FEATURE ENGNEERING
ALTER TABLE HR_DATA 
ADD COLUMN EXPERIENCE_LEVEL VARCHAR(100);

UPDATE HR_DATA
SET EXPERIENCE_LEVEL = CASE
	WHEN EXPERIENCE_YEARS < 3 THEN "Junior"
    WHEN EXPERIENCE_YEARS BETWEEN 3 AND 7 THEN "Mid_level"
    WHEN EXPERIENCE_YEARS > 7 THEN "Senior"
END;
-- CHECK THE RANGE OF SALARY 
SELECT MIN(Salary_INR),MAX(Salary_INR)
FROM HR_DATA;
-- SALARY BAND USING ACTUAL RANGE
ALTER table HR_DATA 
ADD COLUMN SALARY_BAND VARCHAR(100);

UPDATE HR_DATA
SET SALARY_BAND = CASE
	WHEN SALARY_INR < 500000 THEN 'Low(below 5L)'
    WHEN SALARY_INR BETWEEN 500000 AND 1500000 THEN 'Medium (5L-15L)'
    WHEN SALARY_INR BETWEEN 1500001 AND 2500000 THEN 'High (15L-25L'
    ELSE 'Executive (Above 25L)'
END;

-- COUNT BASED ON SALARY RANGE
SELECT Salary_Band, COUNT(*) AS Employee_Count
FROM hr_data
GROUP BY Salary_Band
ORDER BY MIN(Salary_INR);

-- DATA ANALYSIS
-- DEPARTMENT WISE EMPLOYEE COUNT AND AVERAGE SALARY
SELECT DEPARTMENT,COUNT(EMPLOYEE_ID) AS TOTAL_EMPLOYEES,ROUND(AVG(SALARY_INR),2)  AS AVERAGE_SALARY
FROM HR_DATA
GROUP BY DEPARTMENT
ORDER BY TOTAL_EMPLOYEES DESC;
-- EXPERIENCE LEVEL VS AVERAGE SALARY
SELECT EXPERIENCE_LEVEL ,COUNT(EMPLOYEE_ID) AS TOTAL_EMPLOYEES,ROUND(AVG(SALARY_INR),2) AS AVG_SALARY
FROM HR_DATA
GROUP BY EXPERIENCE_LEVEL
ORDER BY AVG_SALARY;

-- TOP 10 HIGHEST PAID EMPLOYEES
SELECT * 
FROM HR_DATA
ORDER BY SALARY_INR desc
LIMIT 10;

-- SALARY BAND DISTRIBUTION
SELECT SALARY_BAND,COUNT(*) AS EMPLOYEE_COUNT
FROM HR_DATA
GROUP BY SALARY_BAND
ORDER BY MIN(SALARY_INR);

-- AVERAGE SALARY BY COUNTRY
SELECT COUNTRY,ROUND(AVG(SALARY_INR),0) AS AVG_SALARY
FROM HR_DATA
GROUP BY COUNTRY
ORDER BY AVG_SALARY;

-- HEADCOUNT BY EMPLOYMENT STATUS
SELECT STATUS,COUNT(*) AS COUNT
FROM HR_DATA
GROUP BY STATUS
ORDER BY COUNT DESC;

-- ATTRITION RATE BY DEPARTMENT
SELECT DEPARTMENT,
	ROUND(SUM(CASE 
		WHEN STATUS in ( 'RESIGNED','terminated','retired') THEN 1 
			ELSE 0 
		END)*100 / COUNT(*),2) AS ATTRITION_RATE
FROM HR_DATA
GROUP BY DEPARTMENT
ORDER BY ATTRITION_RATE DESC;

-- RANDK SALARY BY DEPARTMENT
SELECT DEPARTMENT,FULL_NAME,SALARY_INR,
	RANK() OVER (partition by DEPARTMENT ORDER BY SALARY_INR  DESC) AS SALARY_RANK
    FROM HR_DATA
    order by DEPARTMENT,SALARY_RANK;
    -- LIMIT 10;

-- TOP PERFORMER BY DEPARTMENT
SELECT 
    Department,
    Full_Name,
    Performance_Rating,
    ROW_NUMBER() OVER (PARTITION BY Department ORDER BY Performance_Rating DESC) AS Rank_By_Performance
FROM hr_data
WHERE Performance_Rating IS NOT NULL;

-- CALCULATE SALARY DIFFERENCE FROM DEPARTMENT AVERAGE
SELECT 
    Department,
    Full_Name,
    Salary_INR,
    ROUND(AVG(Salary_INR) OVER (PARTITION BY Department), 2) AS Avg_Salary_Dept,
    Salary_INR - ROUND(AVG(Salary_INR) OVER (PARTITION BY Department), 2) AS Salary_Difference
FROM hr_data
ORDER BY Department;

-- PERCENTILE SALARY POSITION (USING WINDOW FUNCTION)
SELECT 
    Department,
    Full_Name,
    Salary_INR,
    ROUND(PERCENT_RANK() OVER (PARTITION BY Department ORDER BY Salary_INR), 2) AS Salary_Percentile
FROM hr_data
ORDER BY Department, Salary_Percentile DESC;

-- CUMMULATIVE SALARY BY DEPARTMENT
SELECT 
    Department,
    Full_Name,
    Salary_INR,
    SUM(Salary_INR) OVER (PARTITION BY Department ORDER BY Salary_INR DESC) AS Cumulative_Salary
FROM hr_data;

-- CATEGORIZE EMPLOYEES INTO QUATILES
SELECT 
    Department,
    Full_Name,
    Salary_INR,
    NTILE(4) OVER (PARTITION BY Department ORDER BY Salary_INR DESC) AS Salary_Quartile
FROM hr_data;

-- YEAR WISE HIRING TREND
SELECT 
    YEAR(Hire_Date) AS Hire_Year,
    COUNT(*) AS Employees_Hired
FROM hr_data
GROUP BY YEAR(Hire_Date)
ORDER BY Hire_Year;

-- PERFORMANCE AND SALARY RELATIONSHIP
SELECT 
    Performance_Rating,
    ROUND(AVG(Salary_INR),2) AS Avg_Salary,
    COUNT(*) AS Employees
FROM hr_data
GROUP BY Performance_Rating
ORDER BY Performance_Rating DESC;

-- OVERALL SUMMARY
SELECT 
    COUNT(*) AS Total_Employees,
    COUNT(DISTINCT Department) AS Total_Departments,
    COUNT(DISTINCT Country) AS Total_Countries,
    ROUND(AVG(Salary_INR),2) AS Avg_Salary,
    ROUND(SUM(CASE WHEN Status IN ('Resigned','Terminated','Retired') THEN 1 ELSE 0 END)*100/COUNT(*),2) AS Overall_Attrition_Rate
FROM hr_data;
